import * as React from "react";
import "./Icon.scss";

export interface IIconProps {
  type?: string[] | string;
  className?: string;
  style?: any;
}

// Icons generated by IcoMoon tool https://icomoon.io/app/#/select
export default React.memo( ({ type, className = "", style }: IIconProps) => <span
        role="presentation"
        aria-hidden="true"
        style={{...style}}
        className={`icon-${type} ${className}`}
    />);
